# Generated by Django 2.0.10 on 2019-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.IntegerField(default=12345, verbose_name='トークン'),
            preserve_default=False,
        ),
    ]
