# Generated by Django 2.0.10 on 2019-01-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
