# Generated by Django 2.0.10 on 2019-01-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190119_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
